const { Router } = require('express');
const repo = require('./repos/conversations.repo');
const { summarise } = require('./agent/summarise');
const { queueSummaryRepair } = require('./agent/summaryRecovery');
const logger = require('../configs/logger');
const { AppError } = require('./middlewares/errors');

/**
 * Diane's conversations, saved when they END rather than turn by turn.
 *
 * Nothing writes to the database while somebody is talking to her. The
 * browser holds the transcript (it already does, it posts it on every
 * turn) and sends it once, when the orb closes or the page unloads. See
 * web/src/components/agentOrb/useConversationLog.js for how the end is
 * detected and why there is a checkpoint.
 *
 * Admin session only, mounted behind requireSession in app.js.
 */
const router = Router();

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// A transcript this long is a session somebody left open all day, not a
// conversation. Saved anyway; the guard is against a malformed body, not
// against a real user.
const MAX_MESSAGES = 2000;

function cleanList(value, { upper = false } = {}) {
  if (!Array.isArray(value)) return [];
  const out = new Set();
  for (const item of value) {
    const s = String(item ?? '').trim();
    if (s) out.add(upper ? s.toUpperCase() : s);
  }
  return [...out];
}

/**
 * Save a whole conversation. Idempotent on the id.
 *
 * THE END CAN FIRE TWICE. Closing the orb and the tab unloading are two
 * separate signals and a checkpoint may already have written once, so the
 * second call must replace rather than duplicate. The browser owns the id
 * for exactly this reason.
 */
router.post('/conversations', async (req, res, next) => {
  try {
    const {
      id, startedAt, messages, touchedRows, touchedPeople, touchedGroups, touchedCompanies,
    } = req.body || {};

    if (!UUID.test(String(id ?? ''))) {
      return next(new AppError(400, 'id must be a uuid, generated by the client'));
    }
    if (!Array.isArray(messages)) {
      return next(new AppError(400, 'messages must be an array'));
    }

    const clean = messages
      .filter((m) => ['user', 'assistant'].includes(m?.role) && typeof m?.content === 'string')
      .map((m) => ({ role: m.role, content: m.content }))
      .slice(0, MAX_MESSAGES);

    // NOTHING SAID, NOTHING STORED. Opening the orb and closing it again
    // is not a conversation, and an empty row would be a permanent search
    // result with no content.
    if (clean.length === 0) return res.json({ saved: false, reason: 'empty' });

    /**
     * THE SUMMARY IS BEST EFFORT, THE TRANSCRIPT IS NOT.
     *
     * `summarise` returns null rather than throwing, so a model outage
     * costs a searchable paragraph and never the conversation itself.
     * `needingSummary` finds these later.
     *
     * THE CHECKPOINT GETS ONE TOO, which it used to skip on the grounds
     * that half a conversation describes half a decision. True, and the
     * wrong trade: the checkpoint only fires past 50KB, and past 60KB the
     * unload beacon is DROPPED without a word (useConversationLog.js). So
     * the conversations that skipped it were exactly the long ones most
     * likely to end with no summary at all. Half a decision beats none, and
     * it is provisional — the end save summarises the full transcript and
     * `repo.save` replaces this one.
     *
     * It costs at most one extra model call per conversation: the browser
     * checkpoints ONCE, not per turn.
     */
    const memory = await summarise(clean);

    await repo.save({
      id,
      startedAt: startedAt ? new Date(startedAt) : new Date(),
      messages: clean,
      summary: memory?.text ?? null,
      memory,
      touchedRows: cleanList(touchedRows).map(Number).filter(Number.isInteger),
      touchedPeople: cleanList(touchedPeople),
      touchedGroups: cleanList(touchedGroups, { upper: true }),
      touchedCompanies: cleanList(touchedCompanies),
    });

    if (memory) queueSummaryRepair();
    res.json({ saved: true, messages: clean.length, summarised: Boolean(memory) });
  } catch (err) {
    // A failed save must not surface to the admin: the conversation itself
    // already happened and there is nothing for them to do about it. The
    // Logs page carries the detail.
    logger.error({ err }, 'diane: saving a conversation failed');
    next(err);
  }
});

module.exports = { router };
