const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

/**
 * ***************************************************
 * * CONTRACT: an expense's AED comes from its OWN row
 * ***************************************************
 *
 * Nothing about this can be caught by reading a figure: a total converted
 * at today's rate looks exactly like a correct one until somebody edits
 * Settings months later and every saved expense moves. So it is pinned on
 * the SHAPE of the code instead.
 *
 * READ WITH COMMENTS STRIPPED. A doesNotMatch guard over raw source
 * happily matches its own explanatory comment and passes on a broken file.
 */

const here = __dirname;
const api = path.join(here, '..');

const read = (...p) => fs.readFileSync(path.join(...p), 'utf8');

/** Code only. Block comments, line comments and SQL comments all go. */
function codeOf(source) {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/^\s*\/\/.*$/gm, ' ')
    .replace(/^\s*--.*$/gm, ' ');
}

const EXPENSE_FILES = [
  path.join(api, 'expenses.js'),
  path.join(api, 'expenses', 'expenseIdentity.js'),
  path.join(api, 'expenses', 'expenseColumns.js'),
  path.join(api, 'expenses', 'parseExpenses.js'),
  path.join(api, 'expenses', 'buildExpenseSheet.js'),
  path.join(api, 'expenses', 'diffExpenses.js'),
  path.join(api, 'repos', 'expenses.repo.js'),
];

test('EXPENSES NEVER READ THE GLOBAL RATES', () => {
  for (const file of EXPENSE_FILES) {
    const code = codeOf(fs.readFileSync(file, 'utf8'));
    const name = path.basename(file);
    assert.doesNotMatch(code, /fxRates/, `${name} must not reach the rates helper or repo`);
    assert.doesNotMatch(code, /tb_fx_rates/, `${name} must not read tb_fx_rates`);
  }
});

test('expenses read no deal either: it is a standalone ledger', () => {
  for (const file of EXPENSE_FILES) {
    const code = codeOf(fs.readFileSync(file, 'utf8'));
    assert.doesNotMatch(code, /tb_mastersheet/, `${path.basename(file)} must not read the deals`);
  }
});

test('the AED amount is GENERATED by the database, not written', () => {
  const migration = read(api, 'migrations', '055_expenses.sql');
  assert.match(
    migration,
    /aed_amount[\s\S]*?GENERATED ALWAYS AS \(round\(raw_amount \* exchange_rate, 2\)\) STORED/,
  );
});

test('THE TOTAL IS A SUM, NEVER A MULTIPLICATION', () => {
  // SUM(raw_amount) * a rate is the one way this page could still report a
  // figure converted at today's rate. It must not appear anywhere.
  const code = codeOf(read(api, 'repos', 'expenses.repo.js'));
  assert.match(code, /SUM\(aed_amount\)/);
  assert.doesNotMatch(code, /SUM\(raw_amount\)/);
});

test('the repo is the only place expenses touch SQL', () => {
  const route = codeOf(read(api, 'expenses.js'));
  assert.doesNotMatch(route, /pool\./, 'routes call a repo, never the database');
  assert.doesNotMatch(route, /SELECT |INSERT |UPDATE |DELETE FROM/);
});

test('sync_key carries no unique index, now or by accident later', () => {
  // Two identical taxi fares on one day are two real expenses. A unique
  // index here would refuse the second one outright.
  const migration = codeOf(read(api, 'migrations', '055_expenses.sql'));
  assert.match(migration, /CREATE INDEX IF NOT EXISTS tb_expenses_sync_key_idx/);
  assert.doesNotMatch(migration, /UNIQUE[\s\S]*sync_key/);
});

test('the currency check keeps one casing at the database, not just in code', () => {
  const migration = read(api, 'migrations', '055_expenses.sql');
  assert.match(migration, /currency = upper\(currency\)/);
});

/**
 * ===============================
 * * THE TWO IMPORTS MUST NEVER MEET
 * ===============================
 * A deals file and an expenses file that could each reach the other's
 * parser would both get far enough to look like they worked: the headers
 * differ, so the wrong parser reads zero rows and reports an empty file
 * rather than a wrong one. Silent, and the fix is to keep them apart.
 */
test('expenses import and export share NO code with the master sheet', () => {
  const forbidden = [
    'parseImport', 'diffImport', 'importColumns', 'buildWorkbook',
    'buildMasterSheetWorkbook', 'masterSheet/',
  ];
  for (const file of EXPENSE_FILES) {
    const code = codeOf(fs.readFileSync(file, 'utf8'));
    const name = path.basename(file);
    for (const word of forbidden) {
      // dealKey is the one allowed crossing: `fold` is a comparison rule,
      // one per codebase, and a pointer is not a parser.
      if (word === 'masterSheet/' && /masterSheet\/dealKey/.test(code)) continue;
      assert.doesNotMatch(code, new RegExp(word), `${name} must not reach ${word}`);
    }
  }
});

test('the master sheet does not reach into expenses either', () => {
  const sheet = codeOf(read(api, 'masterSheet.js'));
  assert.doesNotMatch(sheet, /expenses/i);
});

test('the expenses upload is its OWN multer, on its own route', () => {
  const route = codeOf(read(api, 'expenses.js'));
  assert.match(route, /const upload = multer\(/);
  assert.match(route, /\/expenses\/import\/preview/);
  // The preview writes nothing; only the commit writes.
  const preview = route.slice(route.indexOf('/expenses/import/preview'));
  const body = preview.slice(0, preview.indexOf('/expenses/import/commit'));
  assert.doesNotMatch(body, /createMany|\.create\(|\.update\(/);
});

test('the export writes the columns the parser reads, one list', () => {
  const builder = codeOf(read(api, 'expenses', 'buildExpenseSheet.js'));
  const parser = codeOf(read(api, 'expenses', 'parseExpenses.js'));
  assert.match(builder, /require\('\.\/expenseColumns'\)/);
  assert.match(parser, /require\('\.\/expenseColumns'\)/);
});

test('THE MONTH IS THE SERVER\'S, never the query string\'s', () => {
  // The admin's clock and the server's are ten hours apart. A browser
  // sending its own month would put two people on two different ledgers at
  // every boundary, and neither would look wrong.
  const route = codeOf(read(api, 'expenses.js'));
  assert.match(route, /const month = currentMonth\(\)/);
  assert.doesNotMatch(route, /query\.month/, 'the month is not a parameter');
  assert.match(route, /res\.json\(\{ \.\.\.result, month/, 'and the page is told which one');
});
