// What must be true after each conversation. Seed (MANBAT, this month): Cleaner payment 250 (07),
// Super 98 petrol 120.43 (06), Taxi Al Barsha to DIFC 45 (05), Team lunch 30 (06), Lunch with client 40 (03),
// Groceries 139.91 (04), Internet bill Sep 2026 471.45 (01), Electricity and water Sep (DEWA) 919.28 (01).
const live = (p) => (p?.kind === 'add' ? p.items.filter((x) => !x.skipped) : []);
const amt = (db, re) => db.find((r) => re.test(r.description))?.amount;
const gone = (db, re) => !db.some((r) => re.test(r.description));
const newRows = (db) => db.filter((r) => !/^(Cleaner payment|Super 98 petrol 38\.6L|Taxi Al Barsha to DIFC|Team lunch|Lunch with client|Groceries|Internet bill Sep 2026|Electricity and water Sep)$/.test(r.description));
const expect = (cond, why) => (cond ? true : why);
const stillWaiting = (reply) => /still waiting|waiting for|is waiting|are waiting|not saved yet/i.test(reply);

module.exports = [
  // ---------- ADDING: typed, messy ----------
  { name: 'add: one typed line', steps: ['taxi to the office 45 paid to careem today'], check: ({ pending }) => expect(live(pending).length === 1 && live(pending)[0].rawAmount === 45, `items ${live(pending).length}`) },
  { name: 'add: two in one line', steps: ['lunch with the team 320 at zuma yesterday, parking 20 RTA'], check: ({ pending }) => expect(live(pending).length === 2, `items ${live(pending).length}`) },
  { name: 'add: someone else spent it', steps: ['Ali bought printer paper 62.50 from office depot on 3 oct'], check: ({ pending }) => expect(live(pending)[0]?.spentBy === 'Ali' && live(pending)[0]?.spentOn === '2026-10-03', JSON.stringify(live(pending)[0]?.spentBy)) },
  { name: 'add: pounds', steps: ['train to leeds £86.40 trainline 6 oct'], check: ({ pending }) => expect(live(pending)[0]?.currency === 'GBP', live(pending)[0]?.currency) },
  { name: 'add: three dates, one line', steps: ['water delivery 45 at masafi on the 1st, 2nd and 3rd of oct'], check: ({ pending }) => expect(live(pending).length === 3, `items ${live(pending).length}`) },
  { name: 'add: a typed list', steps: ['- taxi 45 careem\n- lunch 30 zuma\n- parking 15 rta\nall today, all me'], check: ({ pending }) => expect(live(pending).length === 3 && live(pending).every((x) => x.spentBy), `items ${live(pending).length}`) },
  { name: 'add: commas in amounts', steps: ['rent deposit AED 7,500 to Al Fardan on the 1st, spent by me'], check: ({ pending }) => expect(live(pending)[0]?.rawAmount === 7500, String(live(pending)[0]?.rawAmount)) },
  { name: 'add: then answer and save', steps: ['coffee 18 starbucks', 'today, me', 'yes'], check: ({ db }) => expect(newRows(db).some((r) => r.amount === 18), 'not saved') },
  { name: 'add: answers in one go, messy', steps: ['taxi 45 careem\nlunch 30 zuma', 'both today and both me', 'save'], check: ({ db }) => expect(newRows(db).length === 2, `saved ${newRows(db).length}`) },
  { name: 'add: "ok save them" after a full preview', steps: ['taxi 45 paid to careem today spent by me', 'ok save them'], check: ({ db }) => expect(newRows(db).length === 1, `saved ${newRows(db).length}`) },
  { name: 'add: a large one is flagged, then saved', steps: ['new laptop 25000 apple store today spent by me', 'yes'], check: ({ db }) => expect(newRows(db).some((r) => r.amount === 25000), 'not saved') },

  // ---------- ADDING: EVERY FIELD EXACT (plan item 26, 2026-10-08) ----------
  // What is SAVED, field by field: amount, currency, payee, day, category, who.
  ...[
    ['taxi to the office 45 aed paid to careem on 5 oct, spent by me', 'yes', { amount: 45, currency: 'AED', payee: /careem/i, day: '2026-10-05', category: 'travel' }],
    ['train to leeds £86.40 trainline 6 oct, me', 'yes', { amount: 86.4, currency: 'GBP', payee: /trainline/i, day: '2026-10-06', category: 'travel' }],
    ['super 98 petrol 120 at enoc on 2 oct, me', 'yes', { amount: 120, currency: 'AED', payee: /enoc/i, day: '2026-10-02', category: 'fuel' }],
    ['team lunch 320 at zuma on 4 oct, me', 'yes', { amount: 320, currency: 'AED', payee: /zuma/i, day: '2026-10-04', category: 'food' }],
  ].map(([say, yes, want]) => ({
    name: `exact: ${say}`,
    steps: [say, yes],
    check: ({ db }) => {
      const r = newRows(db)[0];
      const bad = !r ? 'not saved' : [
        Math.abs(r.amount - want.amount) < 0.005 ? null : `amount ${r.amount}`,
        r.currency === want.currency ? null : `currency ${r.currency}`,
        want.payee.test(r.payee ?? '') ? null : `payee ${r.payee}`,
        r.day === want.day ? null : `day ${r.day}`,
        r.category === want.category ? null : `category ${r.category}`,
      ].filter(Boolean).join(', ');
      return expect(!bad, bad);
    },
  })),

  // ---------- ADDING: files ----------
  { name: 'file: taxi receipt', steps: [{ files: ['receipt-02-careem.png'] }], check: ({ pending }) => expect(live(pending)[0]?.rawAmount === 45, String(live(pending)[0]?.rawAmount)) },
  { name: 'file: DEWA pdf', steps: [{ files: ['invoice-01-dewa.pdf'] }], check: ({ pending }) => expect(Math.abs((live(pending)[0]?.rawAmount ?? 0) - 919.28) < 0.01, String(live(pending)[0]?.rawAmount)) },
  { name: 'file: messy csv', steps: [{ files: ['expenses-messy.csv'] }], check: ({ pending }) => expect(live(pending).length === 6, `items ${live(pending).length}`) },
  { name: 'file: word notes', steps: [{ files: ['weekly-expenses.docx'] }], check: ({ pending }) => expect(live(pending).length === 4, `items ${live(pending).length}`) },
  { name: 'file: slides', steps: [{ files: ['costs-review.pptx'] }], check: ({ pending }) => expect(live(pending).length === 3, `items ${live(pending).length}`) },
  { name: 'file: two receipts, then all me and save', steps: [{ files: ['receipt-02-careem.png', 'receipt-07-amazon.png'] }, 'all me', 'yes'], check: ({ db }) => expect(db.length === 10, `saved ${db.length - 8}`) },

  // ---------- NOT ANSWERING YES OR CANCEL (never locked) ----------
  { name: 'unlock: question while a preview waits', steps: ['coffee 18 starbucks today me', 'how much did we spend this month?'], check: ({ last, pending }) => expect(/SPENDING|TOTAL/.test(last) && live(pending).length === 1, 'no answer, or preview lost') },
  { name: 'unlock: question while a change waits', steps: ['change the groceries to 300', 'how much on fuel this month?'], check: ({ last, pending }) => expect(/SPENDING|TOTAL|No expenses found/.test(last) && pending?.kind === 'edit', `last: ${last.slice(0, 60)}`) },
  { name: 'unlock: question while a removal waits', steps: ['remove the cleaner', 'how much this month?'], check: ({ last, pending }) => expect(/SPENDING|TOTAL/.test(last) && (pending?.kind === 'remove' || (pending?.kind === 'edit' && (pending.removes ?? []).length > 0)), `last: ${last.slice(0, 60)}`) },
  { name: 'unlock: new expense while a change waits', steps: ['change the groceries to 300', 'coffee 18 starbucks today me'], check: ({ pending, state, last }) => expect(live(pending).length === 1 || /coffee/i.test(last), `pending ${pending?.kind}`) },
  { name: 'unlock: new expense while a removal waits', steps: ['remove the cleaner', 'coffee 18 starbucks today me'], check: ({ pending, state, last }) => expect(live(pending).length === 1 && ['remove', 'edit'].includes(state.parked?.kind) && /kept the removal/.test(last), `pending ${pending?.kind}, parked ${state.parked?.kind}`) },
  { name: 'unlock: set aside, save the new, the old comes back', steps: ['remove the cleaner', 'coffee 18 starbucks today me', 'yes', 'yes'], check: ({ db }) => expect(gone(db, /Cleaner/) && db.some((r) => r.amount === 18), 'not both done') },
  { name: 'unlock: a change while new expenses wait', steps: ['coffee 18 starbucks today me', 'change the groceries to 300', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300, `groceries ${amt(db, /^Groceries$/)}`) },
  { name: 'unlock: a removal while new expenses wait', steps: ['coffee 18 starbucks today me', 'remove the cleaner', 'yes'], check: ({ db }) => expect(gone(db, /Cleaner/), 'cleaner still there') },
  { name: 'unlock: moving on, then back to save', steps: ['coffee 18 starbucks today me', 'how much this month?', 'yes'], check: ({ db }) => expect(newRows(db).some((r) => r.amount === 18), 'coffee not saved') },
  { name: 'unlock: hi while a change waits', steps: ['change the groceries to 300', 'hi'], check: ({ last }) => expect(/waiting|Groceries/i.test(last), `last: ${last.slice(0, 60)}`) },
  { name: 'unlock: thanks while a removal waits', steps: ['remove the cleaner', 'thanks'], check: ({ pending }) => expect((pending?.kind === 'remove' || (pending?.kind === 'edit' && (pending.removes ?? []).length > 0)), 'removal lost') },
  { name: 'unlock: ignore it and start another change', steps: ['change the groceries to 300', 'never mind that, change the taxi to 50', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50 && amt(db, /^Groceries$/) === 139.91, `taxi ${amt(db, /Taxi/)} groceries ${amt(db, /^Groceries$/)}`) },
  { name: 'unlock: show me the list while a removal waits', steps: ['remove the cleaner', 'show me this month\'s expenses'], check: ({ last, pending }) => expect(/EXPENSES|SPENDING/.test(last) && (pending?.kind === 'remove' || (pending?.kind === 'edit' && (pending.removes ?? []).length > 0)), `last: ${last.slice(0, 60)}`) },

  // ---------- UPDATING ----------
  { name: 'edit: plain', steps: ['change the groceries to 300', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300, String(amt(db, /^Groceries$/))) },
  { name: 'edit: by payee', steps: ['change the zuma lunch to 35', 'yes'], check: ({ db }) => expect(amt(db, /Team lunch/) === 35, String(amt(db, /Team lunch/))) },
  { name: 'edit: by amount', steps: ['the 120.43 one should be 125', 'yes'], check: ({ db }) => expect(amt(db, /petrol/) === 125, String(amt(db, /petrol/))) },
  { name: 'edit: two fields', steps: ['change the taxi payee to uber and amount to 50', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50 && /^uber$/i.test(db.find((r) => /Taxi/.test(r.description))?.payee ?? ''), JSON.stringify(db.find((r) => /Taxi/.test(r.description)))) },
  { name: 'edit: date words', steps: ['fix the date on the internet bill, it was 30 sept', 'yes'], check: ({ db }) => expect(db.find((r) => /Internet/.test(r.description))?.day === '2026-09-30', db.find((r) => /Internet/.test(r.description))?.day) },
  { name: 'edit: arrow', steps: ['taxi 45 -> 50', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'edit: colon, asked change or new', steps: ['groceries: 300', 'change', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300, String(amt(db, /^Groceries$/))) },
  { name: 'edit: dewa bill', steps: ['make the dewa bill 900', 'yes'], check: ({ db }) => expect(amt(db, /Electricity/) === 900, String(amt(db, /Electricity/))) },
  { name: 'edit: last expense', steps: ['update the last expense to 99', 'yes'], check: ({ db }) => expect(db.some((r) => r.amount === 99), 'none at 99') },
  { name: 'edit: a list in one message, asked change or new', steps: ['groceries 300\ntaxi 50\ncleaner 220', 'change', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300 && amt(db, /Taxi/) === 50 && amt(db, /Cleaner/) === 220, `${amt(db, /^Groceries$/)} ${amt(db, /Taxi/)} ${amt(db, /Cleaner/)}`) },
  { name: 'edit: spent by', steps: ['the groceries were spent by Abe', 'yes'], check: ({ db }) => expect(db.find((r) => /^Groceries$/.test(r.description))?.spent_by === 'Abe', db.find((r) => /^Groceries$/.test(r.description))?.spent_by) },
  { name: 'edit: category', steps: ['put the groceries under office', 'yes'], check: ({ db }) => expect(db.find((r) => /^Groceries$/.test(r.description))?.category === 'office', db.find((r) => /^Groceries$/.test(r.description))?.category) },
  { name: 'edit: currency', steps: ['the lunch with client was 40 pounds not aed', 'yes'], check: ({ db }) => expect(db.find((r) => /Lunch with client/.test(r.description))?.currency === 'GBP', db.find((r) => /Lunch with client/.test(r.description))?.currency) },
  { name: 'edit: add to amount', steps: ['add 20 to the taxi', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 65, String(amt(db, /Taxi/))) },
  { name: 'edit: knock off', steps: ['knock 10 off the groceries', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 129.91, String(amt(db, /^Groceries$/))) },
  { name: 'edit: correction mid-way', steps: ['change the groceries to 300', 'no wait, 280', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 280, String(amt(db, /^Groceries$/))) },
  { name: 'edit: list then numbers, messy', steps: ['update expenses', '3 -> 125\n6 add 10', 'yes'], check: ({ db }) => expect(amt(db, /petrol/) === 125, `petrol ${amt(db, /petrol/)}`) },
  { name: 'edit: stack, drop, save', steps: ['change the taxi to 50', 'and the groceries to 300', 'and cleaner 200', 'not the cleaner', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50 && amt(db, /^Groceries$/) === 300 && amt(db, /Cleaner/) === 250, `${amt(db, /Taxi/)} ${amt(db, /^Groceries$/)} ${amt(db, /Cleaner/)}`) },
  { name: 'edit: cancel all', steps: ['change the taxi to 50', 'cancel'], check: ({ db, pending }) => expect(amt(db, /Taxi/) === 45 && !pending, 'not cancelled') },
  { name: 'edit: typo verb and name', steps: ['chnage the grocries to 300', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300, String(amt(db, /^Groceries$/))) },
  { name: 'edit: polite long', steps: ['hey could you please update the taxi amount, it should have been 55 aed', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 55, String(amt(db, /Taxi/))) },

  // ---------- REMOVING ----------
  { name: 'remove: two named', steps: ['remove the taxi and the team lunch', 'yes'], check: ({ db }) => expect(gone(db, /Taxi/) && gone(db, /Team lunch/), 'not both gone') },
  { name: 'remove: by amount', steps: ['delete the 45 aed one', 'yes'], check: ({ db }) => expect(gone(db, /Taxi/), 'taxi still there') },
  { name: 'remove: by payee', steps: ['remove the dewa', 'yes'], check: ({ db }) => expect(gone(db, /Electricity/), 'dewa still there') },
  { name: 'remove: a day', steps: ['get rid of everything from yesterday', 'yes'], check: ({ db }) => expect(gone(db, /petrol/) && gone(db, /Team lunch/), 'yesterday not gone') },
  { name: 'remove: that, after saving', steps: ['coffee 18 starbucks today me', 'yes', 'scrap that'], check: ({ pending, last }) => expect((pending?.kind === 'remove' || (pending?.kind === 'edit' && (pending.removes ?? []).length > 0)) || /undo/i.test(last), `pending ${pending?.kind}`) },
  { name: 'remove: list then numbers', steps: ['remove expenses', '1, 3', 'yes'], check: ({ db }) => expect(gone(db, /Cleaner/) && gone(db, /petrol/), 'not removed') },
  { name: 'remove: stack, swap, save', steps: ['remove the taxi', 'and the cleaner', 'actually no, the petrol', 'yes'], check: ({ db }) => expect(gone(db, /Taxi/) && gone(db, /petrol/) && !gone(db, /Cleaner/), 'wrong ones') },
  { name: 'remove: duplicate reason', steps: ['the dewa bill is a duplicate pls delete', 'yes'], check: ({ db }) => expect(gone(db, /Electricity/), 'still there') },
  { name: 'remove: typo', steps: ['delte the grocries', 'yes'], check: ({ db }) => expect(gone(db, /^Groceries$/), 'still there') },
  { name: 'remove: all lunches', steps: ['remove all the lunches', 'yes'], check: ({ db }) => expect(gone(db, /Team lunch/) && gone(db, /Lunch with client/), 'lunches still there') },

  // ---------- MIXED ----------
  { name: 'mixed: change and remove in one', steps: ['change the taxi to 50 and remove the petrol', 'yes', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50 && gone(db, /petrol/), `taxi ${amt(db, /Taxi/)}, petrol ${gone(db, /petrol/) ? 'gone' : 'there'}`) },
  { name: 'mixed: remove then change', steps: ['remove the petrol and change the taxi to 50', 'yes', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50 && gone(db, /petrol/), `taxi ${amt(db, /Taxi/)}, petrol ${gone(db, /petrol/) ? 'gone' : 'there'}`) },
  { name: 'mixed: save then remove', steps: ['coffee 18 starbucks today me', 'save it and remove the cleaner', 'yes'], check: ({ db }) => expect(newRows(db).some((r) => r.amount === 18) && gone(db, /Cleaner/), 'not both') },

  // ---------- QUESTIONS ----------
  { name: 'ask: month total', steps: ['how much did we spend this month'], check: ({ last }) => expect(/TOTAL/.test(last), last.slice(0, 60)) },
  { name: 'ask: on fuel', steps: ['total on fuel'], check: ({ last }) => expect(/TOTAL|SPENDING/.test(last), last.slice(0, 60)) },
  { name: 'ask: biggest', steps: ['biggest expense this month'], check: ({ last }) => expect(/BIGGEST|Electricity|919/i.test(last), last.slice(0, 80)) },
  { name: 'either: they are new', steps: ['groceries 300', 'new'], check: ({ pending }) => expect(live(pending).length === 1, `pending ${pending?.kind}`) },
  { name: 'ask: at a payee', steps: ['what did we spend at careem'], check: ({ last }) => expect(/45|Careem/i.test(last), last.slice(0, 60)) },
  { name: 'ask: yesterday', steps: ['list yesterday'], check: ({ last }) => expect(/petrol|Team lunch|EXPENSES/i.test(last), last.slice(0, 60)) },
  { name: 'ask: by category', steps: ['how much by category'], check: ({ last }) => expect(/CATEGORY|Food|Bills/i.test(last), last.slice(0, 60)) },
  { name: 'ask: count this week', steps: ['how many expenses this week'], check: ({ last }) => expect(/\d/.test(last) && !/didn't catch/.test(last), last.slice(0, 60)) },

  // ---------- UNDO ----------
  { name: 'undo: after a save', steps: ['coffee 18 starbucks today me', 'yes', 'undo', 'yes'], check: ({ db }) => expect(!newRows(db).some((r) => r.amount === 18), 'coffee still there') },
  { name: 'undo: after a change', steps: ['change the taxi to 50', 'yes', 'undo that', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 45, String(amt(db, /Taxi/))) },
  { name: 'undo: change it back', steps: ['change the taxi to 50', 'yes', 'change it back', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 45, String(amt(db, /Taxi/))) },
  { name: 'undo: bring back removed', steps: ['remove the taxi', 'yes', 'bring it back', 'yes'], check: ({ db }) => expect(!gone(db, /Taxi/), 'not back') },
  // ---------- ROUND 3: messier ----------
  { name: 'r3 add: no payees', steps: ['Taxi 45\nLunch 30\nParking 15'], check: ({ pending }) => expect(live(pending).length === 3, `items ${live(pending).length}`) },
  { name: 'r3 add: amount first', steps: ['45 aed careem taxi'], check: ({ pending }) => expect(live(pending)[0]?.rawAmount === 45, String(live(pending)[0]?.rawAmount)) },
  { name: 'r3 add: by someone', steps: ['paid 300 for office chairs ikea, by Sara'], check: ({ pending }) => expect(/sara/i.test(live(pending)[0]?.spentBy ?? ''), live(pending)[0]?.spentBy) },
  { name: 'r3 add: three on monday', steps: ['uber 23.5, uber 18, uber 31 all on monday'], check: ({ pending }) => expect(live(pending).length === 3 && live(pending).every((x) => x.spentOn === '2026-10-05'), JSON.stringify(live(pending).map((x) => x.spentOn))) },
  { name: 'r3 add: 25k', steps: ['25k for laptops from apple today me'], check: ({ pending }) => expect(live(pending)[0]?.rawAmount === 25000, String(live(pending)[0]?.rawAmount)) },
  { name: 'r3 add: same as saved', steps: ['DEWA 919.28 on the 1st me'], check: ({ pending }) => expect((live(pending)[0]?.doubts ?? []).some((d) => /already saved/.test(d)), JSON.stringify(live(pending)[0]?.doubts)) },
  { name: 'r3 add+edit in one', steps: ['lunch 30 zuma today me and change the taxi to 50'], check: ({ pending, state, log }) => expect(live(pending).length === 1 || pending?.kind === 'edit' || /then/i.test(log.at(-1).reply), `pending ${pending?.kind}`) },
  { name: 'r3 preview: it was 50', steps: ['taxi 45 careem today me', 'actually it was 50', 'yes'], check: ({ db }) => expect(db.some((r) => r.amount === 50 && /taxi/i.test(r.description)), 'not 50') },
  { name: 'r3 preview: drop the second', steps: ['taxi 45 careem today me\nlunch 30 zuma today me', 'remove the second one', 'yes'], check: ({ db }) => expect(db.length === 9, `rows ${db.length}`) },
  { name: 'r3 preview: first was yesterday', steps: ['taxi 45 careem me\nlunch 30 zuma today me', 'the first one was yesterday', 'yes'], check: ({ db }) => expect(db.some((r) => /taxi/i.test(r.description) && r.day === '2026-10-06'), 'date wrong') },
  { name: 'r3 preview: add one more', steps: ['taxi 45 careem today me', 'add parking 20 rta too'], check: ({ pending }) => expect(live(pending).length === 2, `items ${live(pending).length}`) },
  { name: 'r3 preview: bare payee answer', steps: ['flowers for reception 150 today me', 'interflora'], check: ({ pending }) => expect(/interflora/i.test(live(pending)[0]?.payee ?? ''), live(pending)[0]?.payee) },
  { name: 'r3 preview: only the first two', steps: ['taxi 45 careem today me\nlunch 30 zuma today me\nparking 15 rta today me', 'only the first two', 'yes'], check: ({ db }) => expect(db.length === 10, `rows ${db.length}`) },
  { name: 'r3 preview: wait then yes', steps: ['taxi 45 careem today me', 'wait', 'yes'], check: ({ db }) => expect(db.length === 9, `rows ${db.length}`) },
  { name: 'r3 edit: no to', steps: ['change taxi amount 50', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r3 edit: should be', steps: ['taxi should be 50', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r3 edit: equals', steps: ['update taxi = 50', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r3 edit: set at', steps: ['set the groceries amount at 300', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300, String(amt(db, /^Groceries$/))) },
  { name: 'r3 edit: dirhams', steps: ['groceries was actually 300 dirhams', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300, String(amt(db, /^Groceries$/))) },
  { name: 'r3 edit: date yesterday', steps: ['change the petrol date to yesterday', 'yes'], check: ({ db }) => expect(db.find((r) => /petrol/.test(r.description))?.day === '2026-10-06', db.find((r) => /petrol/.test(r.description))?.day) },
  { name: 'r3 edit: description', steps: ['change description of taxi to Taxi to airport', 'yes'], check: ({ db }) => expect(db.some((r) => r.description === 'Taxi to airport'), 'not renamed') },
  { name: "r3 edit: correct, it's 480", steps: ["correct the internet bill, it's 480", 'yes'], check: ({ db }) => expect(amt(db, /Internet/) === 480, String(amt(db, /Internet/))) },
  { name: 'r3 edit: u and pls', steps: ['can u change taxi to 50 pls', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r3 edit: 50 for the taxi not 45', steps: ['50 for the taxi not 45', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r3 remove: three named', steps: ['remove taxi, lunch with client & groceries', 'yes'], check: ({ db }) => expect(gone(db, /Taxi/) && gone(db, /Lunch with client/) && gone(db, /^Groceries$/), 'not all gone') },
  { name: 'r3 remove: with date', steps: ['pls delete the cleaner payment from 7 oct', 'yes'], check: ({ db }) => expect(gone(db, /Cleaner/), 'still there') },
  { name: 'r3 remove: 30 aed lunch', steps: ['take out the 30 aed lunch', 'yes'], check: ({ db }) => expect(gone(db, /Team lunch/), 'still there') },
  { name: 'r3 remove: last 2', steps: ['remove the last 2', 'yes'], check: ({ db }) => expect(db.length === 6, `rows ${db.length}`) },
  { name: 'r3 remove: clear today', steps: ['clear today', 'yes'], check: ({ db }) => expect(gone(db, /Cleaner/), 'today not cleared') },
  { name: 'r3 remove: del', steps: ['del groceries', 'yes'], check: ({ db }) => expect(gone(db, /^Groceries$/), 'still there') },
  { name: 'r3 remove: everything', steps: ['remove everything'], check: ({ db, last }) => expect(db.length === 8 && /\?|Which|REMOVE/.test(last), 'removed without asking') },
  { name: 'r3 ask: total so far', steps: ["what's the total so far"], check: ({ last }) => expect(/TOTAL/.test(last), last.slice(0, 60)) },
  { name: 'r3 ask: by person', steps: ['how much did zayn spend'], check: ({ last }) => expect(/TOTAL|SPENDING/.test(last), last.slice(0, 60)) },
  { name: 'r3 ask: careem list', steps: ['show careem expenses'], check: ({ last }) => expect(/Careem|EXPENSES/i.test(last), last.slice(0, 60)) },
  { name: 'r3 ask: food this week', steps: ['how much on food this week'], check: ({ last }) => expect(/TOTAL|SPENDING|No expenses/.test(last), last.slice(0, 60)) },
  { name: 'r3 ask: today?', steps: ['expenses today?'], check: ({ last }) => expect(/Cleaner|EXPENSES|SPENDING/i.test(last), last.slice(0, 60)) },
  { name: 'r3 unlock: wait no during removal', steps: ['remove the cleaner', 'wait no'], check: ({ db }) => expect(!gone(db, /Cleaner/), 'removed!') },
  { name: 'r3 unlock: hello? during preview', steps: ['taxi 45 careem today me', 'hello?'], check: ({ pending, last }) => expect(live(pending).length === 1 && /waiting|preview/i.test(last), last.slice(0, 80)) },
  { name: 'r3 unlock: receipt while a change waits', steps: ['change the groceries to 300', { files: ['receipt-07-amazon.png'] }, 'all me', 'yes', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300 && db.length === 9, `groceries ${amt(db, /^Groceries$/)} rows ${db.length}`) },
  { name: 'r3 unlock: new expense while picking', steps: ['remove the lunch', 'coffee 18 starbucks today me', 'yes'], check: ({ db }) => expect(db.some((r) => r.amount === 18), 'coffee not saved') },
  // ---------- ROUND 4: Diane, long sessions, minds changed, typos ----------
  { name: 'r4 diane: change', diane: true, steps: ['change the MANBAT groceries to 300', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300, String(amt(db, /^Groceries$/))) },
  { name: 'r4 diane: remove', diane: true, steps: ['remove the dewa bill', 'yes'], check: ({ db }) => expect(gone(db, /Electricity/), 'still there') },
  { name: 'r4 diane: question', diane: true, steps: ['how much did MANBAT spend this month'], check: ({ last }) => expect(/MANBAT/.test(last) && /TOTAL/.test(last), last.slice(0, 80)) },
  { name: 'r4 diane: add', diane: true, steps: ['taxi 45 for MANBAT paid to careem today by Zayn', 'yes'], check: ({ db }) => expect(db.length === 9, `rows ${db.length}`) },
  { name: 'r4 session: add, ask, change, both saved', steps: ['taxi 45 careem today me', 'how much this month', 'change the groceries to 300', 'yes', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300 && db.length === 9, `groceries ${amt(db, /^Groceries$/)} rows ${db.length}`) },
  { name: 'r4 mind: actually change instead', steps: ['remove the cleaner', 'actually just change the cleaner to 200 instead', 'yes'], check: ({ db }) => expect(amt(db, /Cleaner/) === 200, `cleaner ${amt(db, /Cleaner/)}`) },
  { name: 'r4 help while waiting', steps: ['change the taxi to 50', 'help', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r4 typos: two', steps: ['remvoe the clenaer', 'yes'], check: ({ db }) => expect(gone(db, /Cleaner/), 'still there') },
  { name: 'r4 caps and emoji', steps: ['Change TAXI to 50 🙏', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r4 number words', steps: ['change the taxi to fifty', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r4 pounds sign', steps: ['change the lunch with client to £40', 'yes'], check: ({ db }) => expect(db.find((r) => /Lunch with client/.test(r.description))?.currency === 'GBP', db.find((r) => /Lunch with client/.test(r.description))?.currency) },
  { name: 'r4 date in the name', steps: ['the taxi on the 5th was 50', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r4 two fields one target', steps: ['change the taxi to 50 and the date to 6 oct', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50 && db.find((r) => /Taxi/.test(r.description))?.day === '2026-10-06', JSON.stringify(db.find((r) => /Taxi/.test(r.description)))) },
  { name: 'r4 remove 1 with no list', steps: ['remove 1'], check: ({ last }) => expect(/\*1\.\*/.test(last), last.slice(0, 80)) },
  { name: 'r4 save with nothing', steps: ['save'], check: ({ last }) => expect(/nothing waiting/i.test(last), last.slice(0, 80)) },
  { name: 'r4 thanks after save', steps: ['change the taxi to 50', 'yes', 'thanks'], check: ({ last }) => expect(/welcome/i.test(last), last.slice(0, 80)) },
  { name: 'r4 voice-ish', steps: ['uh can you change the um taxi to 50 please', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r4 receipt ask', steps: ['show me the receipt for the taxi'], check: ({ last }) => expect(!/didn't catch|handed/.test(last), last.slice(0, 80)) },
  { name: 'r4 change by date', steps: ['change the expense on 4 oct to 300', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300, String(amt(db, /^Groceries$/))) },
  { name: 'r4 remove by date and payee', steps: ['delete the careem one on the 5th', 'yes'], check: ({ db }) => expect(gone(db, /Taxi/), 'still there') },
  // ---------- ROUND 5: big files, British replies, edges ----------
  { name: 'r5 big sheet: skip a range, answer, save', steps: [{ files: ['expenses-random.xlsx'] }, 'skip 20-25', 'all me', 'yes'], check: ({ db, last }) => expect(db.length > 8 || /Please check|missing|paid to/i.test(last), `rows ${db.length}, last ${last.slice(0, 60)}`) },
  { name: 'r5 big sheet: save the rest', steps: [{ files: ['expenses-random.xlsx'] }, 'all me', 'save the rest'], check: ({ db }) => expect(db.length > 20, `rows ${db.length}`) },
  { name: 'r5 sorted = yes', steps: ['taxi 45 careem today me', 'sorted'], check: ({ db }) => expect(db.length === 9, `rows ${db.length}`) },
  { name: "r5 that's it = yes", steps: ['taxi 45 careem today me', "that's it, save"], check: ({ db }) => expect(db.length === 9, `rows ${db.length}`) },
  { name: 'r5 nah leave it = cancel', steps: ['remove the cleaner', 'nah leave it'], check: ({ db, pending }) => expect(!gone(db, /Cleaner/) && !pending, `pending ${pending?.kind}`) },
  { name: 'r5 hang on, then yes', steps: ['change the taxi to 50', 'hang on', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r5 cheers mate after save', steps: ['change the taxi to 50', 'yes', 'cheers mate'], check: ({ last }) => expect(/welcome|👍/i.test(last), last.slice(0, 60)) },
  { name: 'r5 ta = thanks', steps: ['ta'], check: ({ last }) => expect(!/didn't catch|handed/.test(last), last.slice(0, 60)) },
  { name: 'r5 yes twice', steps: ['change the taxi to 50', 'yes', 'yes'], check: ({ db, last }) => expect(amt(db, /Taxi/) === 50 && /nothing waiting/i.test(last), last.slice(0, 60)) },
  { name: 'r5 undo with nothing', steps: ['undo'], check: ({ last }) => expect(/nothing/i.test(last), last.slice(0, 60)) },
  { name: 'r5 same file twice', steps: [{ files: ['receipt-07-amazon.png'] }, { files: ['receipt-07-amazon.png'] }], check: ({ pending }) => expect(live(pending).length === 1, `items ${live(pending).length}`) },
  { name: 'r5 paste a line back', steps: ['remove Taxi Al Barsha to DIFC · AED 45.00 · 05 Oct · Careem · by Zayn', 'yes'], check: ({ db }) => expect(gone(db, /Taxi/), 'still there') },
  { name: 'r5 change two in a sentence', steps: ['groceries should be 300 and the taxi 50', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 300 && amt(db, /Taxi/) === 50, `${amt(db, /^Groceries$/)} ${amt(db, /Taxi/)}`) },
  { name: 'r5 remove with because', steps: ['remove the team lunch because it was personal', 'yes'], check: ({ db }) => expect(gone(db, /Team lunch/), 'still there') },
  { name: 'r5 bin it after preview of a saved one', steps: ['show me the groceries', 'bin it', 'yes'], check: ({ db, last }) => expect(gone(db, /^Groceries$/) || /which/i.test(last), last.slice(0, 60)) },
  { name: 'r5 lower case everything', steps: ['change the dewa to 900 pls ta', 'yes'], check: ({ db }) => expect(amt(db, /Electricity/) === 900, String(amt(db, /Electricity/))) },
  { name: 'r5 spent by fix while preview', steps: ['taxi 45 careem today', 'it was Ali', 'yes'], check: ({ db }) => expect(db.some((r) => /^Ali/.test(r.spent_by ?? '')), `spent by: ${db.filter((r) => r.amount === 45).map((r) => r.spent_by).join(', ')}`) },
  { name: 'r5 payee fix while preview', steps: ['flowers 150 today me', 'paid to interflora', 'yes'], check: ({ db }) => expect(db.some((r) => /interflora/i.test(r.payee ?? '')), 'payee missing') },
  { name: 'r5 cancel then new', steps: ['taxi 45 careem today me', 'cancel', 'lunch 30 zuma today me', 'yes'], check: ({ db }) => expect(db.length === 9 && db.some((r) => r.amount === 30 && !/Team lunch/.test(r.description)), `rows ${db.length}`) },
  // ---------- ROUND 6: THE PLANNER BENCHMARK (written before the planner) ----------
  // The numbered list for "update zayn expenses": 1 Cleaner, 2 Team lunch, 3 Petrol, 4 Taxi,
  // 5 Groceries, 6 Lunch with client, 7 DEWA, 8 Internet.
  { name: 'r6 screenshot list', steps: ['update zayn expenses', '1. Make it 500\n2. Change it to Client dinner at Zuma and AED 150\n3. Add 80\n4. Deduct 40\n5. Add 50 to it and make date spent oct 1\n8. Internet bill make it 1299', 'yes'],
    check: ({ db }) => expect(amt(db, /Cleaner/) === 500 && db.some((r) => /Client dinner/.test(r.description) && r.amount === 150) && amt(db, /petrol/) === 200.43 && amt(db, /Taxi/) === 5 && db.some((r) => /^Groceries$/.test(r.description) && r.amount === 189.91 && r.day === '2026-10-01') && amt(db, /Internet/) === 1299, JSON.stringify(db.map((r) => `${r.description}:${r.amount}:${r.day}`))) },
  { name: 'r6 three ops one message', steps: ['change the taxi to 50, bin the petrol and the groceries were actually 150', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50 && gone(db, /petrol/) && amt(db, /^Groceries$/) === 150, `${amt(db, /Taxi/)} ${gone(db, /petrol/)} ${amt(db, /^Groceries$/)}`) },
  { name: 'r6 amount and date', steps: ['the cleaner should be 220 and move it to the 6th', 'yes'], check: ({ db }) => expect(amt(db, /Cleaner/) === 220 && db.find((r) => /Cleaner/.test(r.description))?.day === '2026-10-06', JSON.stringify(db.find((r) => /Cleaner/.test(r.description)))) },
  { name: 'r6 two named two values', steps: ['make the team lunch 35 and the lunch with client 45', 'yes'], check: ({ db }) => expect(amt(db, /Team lunch/) === 35 && amt(db, /Lunch with client/) === 45, `${amt(db, /Team lunch/)} ${amt(db, /Lunch with client/)}`) },
  { name: 'r6 both 100', steps: ['taxi and petrol both 100', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 100 && amt(db, /petrol/) === 100, `${amt(db, /Taxi/)} ${amt(db, /petrol/)}`) },
  { name: 'r6 all lunches 50', steps: ['all lunches this month should be 50', 'yes'], check: ({ db }) => expect(amt(db, /Team lunch/) === 50 && amt(db, /Lunch with client/) === 50, `${amt(db, /Team lunch/)} ${amt(db, /Lunch with client/)}`) },
  { name: 'r6 percent', steps: ['increase the groceries by 10%', 'yes'], check: ({ db }) => expect(Math.abs(amt(db, /^Groceries$/) - 153.9) < 0.02, String(amt(db, /^Groceries$/))) },
  { name: 'r6 amount and payee', steps: ["groceries was 139.91 but it's actually 149.91, also it was paid at lulu not carrefour", 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 149.91 && /lulu/i.test(db.find((r) => /^Groceries$/.test(r.description))?.payee ?? ''), JSON.stringify(db.find((r) => /^Groceries$/.test(r.description)))) },
  { name: 'r6 rename and category', steps: ['rename the dewa one to Electricity Oct and set category bills', 'yes'], check: ({ db }) => expect(db.some((r) => r.description === 'Electricity Oct'), 'not renamed') },
  { name: 'r6 mistake taxi', steps: ['I made a mistake on the taxi, it was 54 not 45', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 54, String(amt(db, /Taxi/))) },
  { name: 'r6 the cleaner one, delete it', steps: ['the cleaner one, delete it', 'yes'], check: ({ db }) => expect(gone(db, /Cleaner/), 'still there') },
  { name: 'r6 kill the last two', steps: ['kill the last two expenses', 'yes'], check: ({ db }) => expect(gone(db, /Electricity/) && gone(db, /Internet/), `rows ${db.length}`) },
  { name: 'r6 except', steps: ['remove everything from the 6th except the petrol', 'yes'], check: ({ db }) => expect(gone(db, /Team lunch/) && !gone(db, /petrol/), 'wrong') },
  { name: 'r6 by payees', steps: ['remove all careem and enoc ones', 'yes'], check: ({ db }) => expect(gone(db, /Taxi/) && gone(db, /petrol/), 'not both') },
  { name: 'r6 list remove ranges', steps: ['update zayn expenses', 'remove 1, 3 and 5-6', 'yes'], check: ({ db }) => expect(gone(db, /Cleaner/) && gone(db, /petrol/) && gone(db, /^Groceries$/) && gone(db, /Lunch with client/) && !gone(db, /Taxi/), `rows ${db.length}`) },
  { name: 'r6 list change and remove', steps: ['update zayn expenses', 'change 2 to 35 and remove 7', 'yes'], check: ({ db }) => expect(amt(db, /Team lunch/) === 35 && gone(db, /Electricity/), `${amt(db, /Team lunch/)} ${gone(db, /Electricity/)}`) },
  { name: 'r6 list number words', steps: ['update zayn expenses', 'number 4 make it 50 pls and number 8 too 500'], check: ({ pending }) => expect(pending?.kind === 'edit' && (pending.items ?? []).length === 2, `pending ${pending?.kind} ${(pending?.items ?? []).length}`) },
  { name: 'r6 the third one', steps: ['update zayn expenses', 'the third one to 130', 'yes'], check: ({ db }) => expect(amt(db, /petrol/) === 130, String(amt(db, /petrol/))) },
  { name: 'r6 first and last', steps: ['remove expenses', 'scrap the first and last', 'yes'], check: ({ db }) => expect(gone(db, /Cleaner/) && gone(db, /Internet/), 'not both') },
  { name: 'r6 change it again after save', steps: ['change the taxi to 50', 'yes', 'change it to 60', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 60, String(amt(db, /Taxi/))) },
  { name: 'r6 ask food and travel', steps: ["what's the total for food and travel this month"], check: ({ last }) => expect(/TOTAL|SPENDING/.test(last) && !/didn't catch/.test(last), last.slice(0, 80)) },
  { name: 'r6 ask the 6th', steps: ['how much did we spend on the 6th'], check: ({ last }) => expect(/150\.43|TOTAL/.test(last), last.slice(0, 80)) },
  { name: 'r6 ask over 100', steps: ['show me everything over 100 aed'], check: ({ last }) => expect(/Cleaner|Electricity|Internet|EXPENSES/i.test(last) && !/didn't catch/.test(last), last.slice(0, 80)) },
  { name: 'r6 rambling fix', steps: ['hey so i was checking and the taxi from al barsha should be 50 since the driver charged extra, can you fix that', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, String(amt(db, /Taxi/))) },
  { name: 'r6 date and amount thanks', steps: ['can you set the date of the groceries to yesterday and the amount to 150 thanks', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 150 && db.find((r) => /^Groceries$/.test(r.description))?.day === '2026-10-06', JSON.stringify(db.find((r) => /^Groceries$/.test(r.description)))) },
  { name: 'r6 swap amounts', steps: ['swap the amounts of the taxi and the petrol', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 120.43 && amt(db, /petrol/) === 45, `${amt(db, /Taxi/)} ${amt(db, /petrol/)}`) },
  { name: 'r6 in pounds', steps: ['the lunch with client was in pounds', 'yes'], check: ({ db }) => expect(db.find((r) => /Lunch with client/.test(r.description))?.currency === 'GBP', db.find((r) => /Lunch with client/.test(r.description))?.currency) },
  { name: 'r6 payee change', steps: ['change the payee on the cleaner payment to Ahmed Khan', 'yes'], check: ({ db }) => expect(db.find((r) => /Cleaner/.test(r.description))?.payee === 'Ahmed Khan', db.find((r) => /Cleaner/.test(r.description))?.payee) },
  { name: 'r6 two under travel', steps: ['put the taxi and petrol under travel', 'yes'], check: ({ db }) => expect(db.find((r) => /Taxi/.test(r.description))?.category === 'travel' && db.find((r) => /petrol/.test(r.description))?.category === 'travel', 'categories') },
  { name: 'r6 never mind leave it', steps: ['change the taxi to 50', 'actually never mind, leave it'], check: ({ db, pending }) => expect(amt(db, /Taxi/) === 45 && !pending, `pending ${pending?.kind}`) },
  { name: 'r6 yes but first', steps: ['change the taxi to 50', 'yes but make it 55 first', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 55, String(amt(db, /Taxi/))) },
  { name: 'r6 category for a day', steps: ['set every expense from yesterday to category food', 'yes'], check: ({ db }) => expect(db.find((r) => /petrol/.test(r.description))?.category === 'food' && db.find((r) => /Team lunch/.test(r.description))?.category === 'food', 'categories') },
  { name: 'r6 the 45 one is 47', steps: ['the 45 one is actually 47', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 47, String(amt(db, /Taxi/))) },
  { name: 'r6 the one i added last', steps: ['delete the one i added last', 'yes'], check: ({ db }) => expect(gone(db, /Electricity/), 'not the last added') },
  { name: 'r6 which lunch then pick by words', steps: ['change the lunch to 35', 'the team one', 'yes'], check: ({ db }) => expect(amt(db, /Team lunch/) === 35, String(amt(db, /Team lunch/))) },
  { name: 'r6 two wrong ones', steps: ['groceries 4 oct and cleaner 7 oct are both wrong, they should be 150 and 200', 'yes'], check: ({ db }) => expect(amt(db, /^Groceries$/) === 150 && amt(db, /Cleaner/) === 200, `${amt(db, /^Groceries$/)} ${amt(db, /Cleaner/)}`) },
  { name: 'r6 change waits, remove too', steps: ['change the taxi to 50', 'and remove the dewa', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50 && gone(db, /Electricity/), `${amt(db, /Taxi/)} ${gone(db, /Electricity/)}`) },
  { name: 'r6 removal waits, change too', steps: ['remove the dewa', 'also make the taxi 50', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50 && gone(db, /Electricity/), `${amt(db, /Taxi/)} ${gone(db, /Electricity/)}`) },
  { name: 'r6 preview then change saved', steps: ['coffee 18 starbucks today me', 'oh and change the taxi to 50 as well', 'yes', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50 && db.some((r) => r.amount === 18), `${amt(db, /Taxi/)} coffee ${db.some((r) => r.amount === 18)}`) },
  { name: 'r6 change and save in one', steps: ['change cleaner to 200 and save it', 'yes'], check: ({ db }) => expect(amt(db, /Cleaner/) === 200, String(amt(db, /Cleaner/))) },
  { name: 'r6 most expensive', steps: ['which is our most expensive this month'], check: ({ last }) => expect(/BIGGEST|Electricity|919/i.test(last), last.slice(0, 80)) },
  { name: 'r6 remove duplicate dewa', steps: ['remove the duplicate dewa', 'yes'], check: ({ db }) => expect(gone(db, /Electricity/), 'still there') },
  { name: 'r6 halve it', steps: ['the internet bill should be half', 'yes'], check: ({ db }) => expect(Math.abs(amt(db, /Internet/) - 235.73) < 0.02, String(amt(db, /Internet/))) },
  { name: 'bulk 1-6 spent by laud', steps: ["update zayn's expenses", '1-6 spent by laud', 'yes'], check: ({ db }) => expect(db.filter((r) => /laud/i.test(r.spent_by ?? '')).length === 6, `spent by laud: ${db.filter((r) => /laud/i.test(r.spent_by ?? '')).length}`) },
  { name: 'r6 move a date by days',steps: ['move the taxi one day later', 'yes'], check: ({ db }) => expect(db.find((r) => /Taxi/.test(r.description))?.day === '2026-10-06', db.find((r) => /Taxi/.test(r.description))?.day) },

  // ---------- PICKING LINES OF A WAITING PREVIEW (2026-10-08) ----------
  // the list: 1 Cleaner, 2 Team lunch, 3 petrol, 4 Taxi, 5 Groceries, 6 Lunch with client, 7 DEWA, 8 Internet
  { name: 'pick: pls only 1-3 of six', steps: ["update zayn's expenses", '1-6 spent by gloria', 'pls only 1-3', 'yes'], check: ({ db }) => expect(db.filter((r) => /gloria/i.test(r.spent_by ?? '')).length === 3, `gloria: ${db.filter((r) => /gloria/i.test(r.spent_by ?? '')).length}`) },
  { name: 'pick: 1-3 only', steps: ["update zayn's expenses", '1-6 spent by gloria', '1-3 only', 'yes'], check: ({ db }) => expect(db.filter((r) => /gloria/i.test(r.spent_by ?? '')).length === 3, `gloria: ${db.filter((r) => /gloria/i.test(r.spent_by ?? '')).length}`) },
  { name: 'pick: not 5-6', steps: ["update zayn's expenses", '1-6 spent by gloria', 'not 5-6', 'yes'], check: ({ db }) => expect(db.filter((r) => /gloria/i.test(r.spent_by ?? '')).length === 4 && !/gloria/i.test(db.find((r) => /^Groceries$/.test(r.description))?.spent_by ?? ''), 'wrong ones') },
  { name: 'pick: except 2', steps: ["update zayn's expenses", '1-6 spent by gloria', 'except 2', 'yes'], check: ({ db }) => expect(db.filter((r) => /gloria/i.test(r.spent_by ?? '')).length === 5 && !/gloria/i.test(db.find((r) => /Team lunch/.test(r.description))?.spent_by ?? ''), 'team lunch changed') },
  { name: 'pick: only the first two', steps: ["update zayn's expenses", '1-6 spent by gloria', 'only the first 2', 'yes'], check: ({ db }) => expect(db.filter((r) => /gloria/i.test(r.spent_by ?? '')).length === 2, `gloria: ${db.filter((r) => /gloria/i.test(r.spent_by ?? '')).length}`) },
  { name: 'pick: a number not there', steps: ["update zayn's expenses", '1-6 spent by gloria', 'only 1-9'], check: ({ last, pending }) => expect(/only 6/.test(last) && (pending?.items ?? []).length === 6, last.slice(0, 80)) },
  { name: 'pick: a removal, only 1', steps: ['remove the taxi and the team lunch', 'only 1', 'yes'], check: ({ db }) => expect(gone(db, /Taxi/) !== gone(db, /Team lunch/), 'both or neither gone') },
  { name: 'pick: the preview is numbered', steps: ["update zayn's expenses", '1-3 spent by gloria'], check: ({ last }) => expect(/\*1\.\*[\s\S]*\*2\.\*[\s\S]*\*3\.\*/.test(last) && /only 1-2/.test(last), last.slice(0, 120)) },
  { name: 'pick: now the rest', steps: ["update zayn's expenses", '1-6 spent by gloria', 'only 1-3', 'yes', 'now the rest to abe', 'yes'], check: ({ db }) => expect(db.filter((r) => /^abe$/i.test(r.spent_by ?? '')).length === 3, `abe: ${db.filter((r) => /^abe$/i.test(r.spent_by ?? '')).length}`) },

  // ---------- LISTS ----------
  { name: 'list: a question numbers its list', steps: ["show me this month's expenses", '1-3 spent by abe', 'yes'], check: ({ db }) => expect(db.filter((r) => /^abe$/i.test(r.spent_by ?? '')).length === 3, `abe: ${db.filter((r) => /^abe$/i.test(r.spent_by ?? '')).length}`) },
  { name: 'list: sort by amount', steps: ["show me this month's expenses", 'sort by amount'], check: ({ last }) => expect(/SORTED BY AMOUNT/.test(last) && /\*1\.\* Electricity/.test(last), last.slice(0, 120)) },
  { name: 'list: only food', steps: ["show me this month's expenses", 'only food'], check: ({ last }) => expect(/only food/.test(last) && !/Cleaner/.test(last), last.slice(0, 120)) },
  { name: 'list: hide the cleaner', steps: ["show me this month's expenses", 'hide the cleaner'], check: ({ last }) => expect(/7 OF 8/.test(last) && !/Cleaner/.test(last), last.slice(0, 120)) },
  { name: 'list: still on screen after a question', steps: ["show me this month's expenses", 'how much this month?', '4 to 50', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 50, `taxi ${amt(db, /Taxi/)}`) },

  // ---------- SMARTER CHANGES ----------
  { name: 'change: by a rule, over 400', steps: ['make everything over 400 spent by abe', 'yes'], check: ({ db }) => expect(db.filter((r) => /^abe$/i.test(r.spent_by ?? '')).length === 2, `abe: ${db.filter((r) => /^abe$/i.test(r.spent_by ?? '')).length}`) },
  { name: 'change: a value per range', steps: ["update zayn's expenses", '1-2 spent by gloria, 3-4 spent by abe', 'yes'], check: ({ db }) => expect(db.filter((r) => /gloria/i.test(r.spent_by ?? '')).length === 2 && db.filter((r) => /^abe$/i.test(r.spent_by ?? '')).length === 2, 'per range wrong') },
  { name: 'change: split one in two', steps: ['split the dewa bill between gloria and abe', 'yes'], check: ({ db }) => expect(db.filter((r) => /Electricity/.test(r.description)).length === 2 && Math.abs(db.filter((r) => /Electricity/.test(r.description)).reduce((n, r) => n + r.amount, 0) - 919.28) < 0.01, 'split wrong') },
  { name: 'change: clear the payee', steps: ['no payee on the taxi', 'yes'], check: ({ db }) => expect(!db.find((r) => /Taxi/.test(r.description))?.payee, db.find((r) => /Taxi/.test(r.description))?.payee) },
  { name: 'change: copy a date', steps: ["update zayn's expenses", "make 4's date the same as 1", 'yes'], check: ({ db }) => expect(db.find((r) => /Taxi/.test(r.description))?.day === '2026-10-07', db.find((r) => /Taxi/.test(r.description))?.day) },
  { name: 'change: 5% on several', steps: ["update zayn's expenses", 'add 5% to 4 and 5', 'yes'], check: ({ db }) => expect(Math.abs(amt(db, /Taxi/) - 47.25) < 0.01 && Math.abs(amt(db, /^Groceries$/) - 146.91) < 0.02, `${amt(db, /Taxi/)} ${amt(db, /^Groceries$/)}`) },
  { name: 'change: do the same for another', steps: ['change the taxi to spent by abe', 'yes', 'do the same for the groceries', 'yes'], check: ({ db }) => expect(/^abe$/i.test(db.find((r) => /^Groceries$/.test(r.description))?.spent_by ?? ''), db.find((r) => /^Groceries$/.test(r.description))?.spent_by) },
  { name: 'change: correcting yourself', steps: ['change the taxi to spent by gloria... no wait, abe', 'yes'], check: ({ db }) => expect(/^abe$/i.test(db.find((r) => /Taxi/.test(r.description))?.spent_by ?? ''), db.find((r) => /Taxi/.test(r.description))?.spent_by) },
  { name: 'change: asks only the missing value', steps: ['update the spent by of the taxi', 'abe', 'yes'], check: ({ db }) => expect(/^abe$/i.test(db.find((r) => /Taxi/.test(r.description))?.spent_by ?? ''), db.find((r) => /Taxi/.test(r.description))?.spent_by) },

  // ---------- SAFETY ----------
  { name: 'safety: a 100x jump is warned', steps: ['change the taxi to 4500'], check: ({ last }) => expect(/100× more/.test(last), last.slice(-160)) },
  { name: 'safety: a big change needs yes N', steps: ['make the dewa bill 15000', 'yes', 'yes 1'], check: ({ db }) => expect(amt(db, /Electricity/) === 15000, String(amt(db, /Electricity/))) },
  { name: 'safety: a big change, a plain yes waits', steps: ['make the dewa bill 15000', 'yes'], check: ({ db, last }) => expect(amt(db, /Electricity/) === 919.28 && /yes 1/.test(last), last.slice(0, 80)) },
  { name: 'safety: a future date is warned', steps: ['change the taxi date to 20 dec'], check: ({ last }) => expect(/in the future/.test(last), last.slice(-160)) },

  // ---------- CONVERSATION ----------
  { name: 'talk: total as if saved', steps: ["update zayn's expenses", '1-3 spent by abe', 'how much did abe spend this month after this?'], check: ({ last, pending }) => expect(/As if/.test(last) && pending?.kind === 'edit', last.slice(0, 120)) },
  { name: 'talk: only 1-3 and remove 5', steps: ["update zayn's expenses", '1-4 spent by gloria', 'only 1-3, and remove 5', 'yes'], check: ({ db }) => expect(db.filter((r) => /gloria/i.test(r.spent_by ?? '')).length === 3 && gone(db, /^Groceries$/), 'not both') },

  // ---------- AFTER SAVING ----------
  { name: 'after: recap who has what', steps: ['change the taxi to spent by abe', 'yes'], check: ({ last }) => expect(/Abe now has 1 expense this month/i.test(last), last.slice(-120)) },
  { name: 'after: undo only 2', steps: ["update zayn's expenses", '1-3 spent by abe', 'yes', 'undo only 2', 'yes'], check: ({ db }) => expect(db.filter((r) => /^abe$/i.test(r.spent_by ?? '')).length === 2 && !/^abe$/i.test(db.find((r) => /Team lunch/.test(r.description))?.spent_by ?? ''), 'wrong one put back') },
  { name: 'after: undo the last 2 things', steps: ['change the taxi to 50', 'yes', 'change the groceries to 300', 'yes', 'undo the last 2 things', 'yes'], check: ({ db }) => expect(amt(db, /Taxi/) === 45 && amt(db, /^Groceries$/) === 139.91, `${amt(db, /Taxi/)} ${amt(db, /^Groceries$/)}`) },
  { name: 'after: undo by the new value', steps: ['change the taxi to spent by abe', 'yes', 'change the groceries to 300', 'yes', 'undo the abe change', 'yes'], check: ({ db }) => expect(!/^abe$/i.test(db.find((r) => /Taxi/.test(r.description))?.spent_by ?? '') && amt(db, /^Groceries$/) === 300, 'wrong one undone') },
  { name: 'after: what did you just change', steps: ['change the taxi to 50', 'yes', 'what did you just change?'], check: ({ last }) => expect(/Last thing you did/.test(last) && /Taxi/.test(last), last.slice(0, 120)) },
  { name: 'after: who changed 4', steps: ['change the taxi to 50', 'yes', "show me this month's expenses", 'who changed 4?'], check: ({ last }) => expect(/Changed by/.test(last), last.slice(0, 160)) },

  // ---------- FINDING ----------
  { name: 'find: search by text', steps: ['find careem'], check: ({ last }) => expect(/WITH "CAREEM"/.test(last) && /Taxi/.test(last), last.slice(0, 120)) },
  { name: 'find: missing payee, filled by number', steps: ['no payee on the taxi', 'yes', 'which have no payee?', '1 careem', 'yes'], check: ({ db }) => expect(/careem/i.test(db.find((r) => /Taxi/.test(r.description))?.payee ?? ''), db.find((r) => /Taxi/.test(r.description))?.payee) },
  { name: 'find: receipt for a list number', steps: ["show me this month's expenses", 'receipt for 2'], check: ({ last }) => expect(/2\. Team lunch/.test(last), last.slice(0, 120)) },

  // ---------- SETTLING (the CRM admin only) ----------
  { name: 'settle: refused on WhatsApp', steps: ["show me this month's expenses", 'settle 1-3'], check: ({ last }) => expect(/Only the CRM admin/.test(last), last.slice(0, 80)) },
];
