// ***************************************************
// * Design mockups for the CRM, generated by OpenAI
// ***************************************************
//
// One shot, run by hand, never part of a build. It asks an image model for
// a mockup of each CRM page in the white and yellow theme and writes the
// PNGs where the app can serve them.
//
//   node tools/designMockups.mjs            every page
//   node tools/designMockups.mjs dashboard  one of them
//
// WHY web/public AND NOT api/public. `api/public` is a build artefact:
// vite.config.js writes it with `emptyOutDir: true`, so the next
// `npm run build` deletes anything else living there. `web/public` is
// Vite's static folder, copied into that output on every build, so these
// survive and are still served at /designs/<page>.png.
//
// The key is `AI_API_KEY` from crm/api/.env, the one the agent already
// uses. It is read, never printed, and never written anywhere.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const ENV_FILE = path.join(ROOT, 'crm', 'api', '.env');
const OUT_DIR = path.join(ROOT, 'crm', 'web', 'public', 'designs');

// gpt-image-1 renders legible text in a UI mockup, which is the whole point
// of a dashboard design. dall-e-3 is the fallback for a key that has not
// been verified for it; its mockups are prettier and its labels are
// gibberish, so it is second choice rather than an equal one.
const MODELS = [
  { model: 'gpt-image-1', size: '1536x1024', extra: { quality: 'high' } },
  { model: 'dall-e-3', size: '1792x1024', extra: { quality: 'hd', response_format: 'b64_json' } },
];

// ===============================
// * The look, written once
// ===============================
// Every prompt gets this, so the eight pages read as one product rather
// than eight designs that happen to share a colour.
const HOUSE_STYLE = `
Style: a modern, premium B2B SaaS admin dashboard UI design mockup, shown
flat and straight on as a full desktop screen at 1440px wide. Photorealistic
UI rendering, not a sketch, not a wireframe, no browser chrome, no laptop
frame, no hands, no people.

Colour: a white and yellow theme. Background is white and very light warm
grey. The accent is a saturated golden yellow used for the active nav item,
primary buttons, key figures, chart fills, focus rings and small status
pips. Body text is near black; secondary text is warm grey. Yellow is an
accent and never a large flat fill behind text.

Form: crisp and square. Sharp or barely rounded corners, hairline light grey
borders, generous white space, a clear type hierarchy with small uppercase
letterspaced column headers. Flat design, subtle shadows at most, no
gradients, no glassmorphism, no neon, no dark mode.

Layout: a narrow left sidebar, a slim top bar with a search field and an
account control, and the page content filling the rest.

THE SIDEBAR IS ALWAYS THE SAME AND ALWAYS THESE SEVEN ITEMS, in this order,
each with a small line icon: "Dashboard", "Master sheet", "People",
"Companies", "Flagged", "Logs", "Settings". Above them the product name
"WHATBOT CRM" in small bold letters. At the foot of the sidebar a "Sign out"
item. The item for the page being shown is the highlighted yellow one and no
other. Do not invent nav items, and do not use generic SaaS ones such as
Customers, Invoices, Orders, Products or Reports.

Realistic, readable English labels, British spelling, and plausible data:
people's full names, company names, and money in pounds sterling.
`.trim();

const PAGES = {
  dashboard: `${HOUSE_STYLE}

Page: the DASHBOARD landing screen. A row of four KPI stat cards across the
top reading "Owed this month", "Collected", "Outstanding" and "Active
deals", each with a large figure in pounds sterling and a small change
indicator. Below them, a wide bar chart of monthly totals with yellow bars,
and beside it a donut chart splitting deals by group. Underneath, a compact
table titled "Needs attention" listing a few rows of person, company and a
short reason, each with a small yellow warning pip.`,

  'master-sheet': `${HOUSE_STYLE}

Page: the MASTER SHEET, a dense wide data table, the heart of the product.
Toolbar above it with a search field, filter and column buttons, a month
selector reading "September 2026", and yellow "Upload sheet" and "Export"
buttons. The table has many columns and a horizontal scrollbar. The first
four columns (a checkbox, Group, Company, Person) are visibly frozen with a
subtle shadow where the freeze ends. Columns include Role, Amount, Payment
start, Preset month, Should be paid, Paid, Status. Money is right aligned.
Two small pill badges appear in a Status column reading "Active" and
"Ended". A couple of cells carry a small yellow warning icon. A footer row
shows a grand total in bold. Pagination bottom right.`,

  people: `${HOUSE_STYLE}

Page: the PEOPLE list. A toolbar with a search field, a filter panel button
and a yellow "Add person" button. Below, a table of people: name, the
companies they work with, a monthly amount, an "Add on %" column and a
"Fee %" column, and a small pill reading "Paying" or "Ended". Each row has a
small avatar circle with initials. A filter panel is open on the right with
grouped checkboxes and a visible "Clear" link.`,

  'person-detail': `${HOUSE_STYLE}

Page: a PERSON DETAIL screen. A breadcrumb reading "People / Craig
Sterling". A header card with the person's name, email and two small toggle
switches labelled "Should be paid" and "Paid". Below it a panel titled
"Companies" listing three company rows, each with a role, a group, a monthly
amount and a small trash icon. Beside it a "Breakdown" card showing labelled
rows: subtotal, an "Add on 5%" row, a "Fee 2%" row, and a bold total. A
"History" list of recent changes runs down the right.`,

  companies: `${HOUSE_STYLE}

Page: the COMPANIES list. A grid of company cards, each with the company
name, a small tier label such as "Visa co", "T3" or "Benched", a count of
handlers, and a status pip reading "Active" or "Closed". A yellow "Add
company" button in the toolbar, and a segmented control switching between
grid and table views.`,

  flagged: `${HOUSE_STYLE}

Page: the FLAGGED screen, a review queue. Tabs across the top reading
"Open", "In progress" and "Resolved" with counts. Below, a list of cards,
each holding a short problem title, the person and company it concerns, a
timestamp, and two buttons, one yellow. A left rail of filter checkboxes.
Small yellow warning triangles beside the more serious rows.`,

  settings: `${HOUSE_STYLE}

Page: the SETTINGS screen. A vertical list of setting sections on the left
(General, Payment rules, Locations, Account) with the middle one selected in
yellow. The panel on the right shows a form: a labelled toggle switch reading
"Use end dates when deciding what is owed", a group of radio options, two
text fields with small floating labels, and a yellow "Save changes" button
bottom right. Plenty of white space, a hairline divider between each
setting, and short grey helper text under each control.`,

  logs: `${HOUSE_STYLE}

Page: the LOGS screen, a technical readout. A filter bar with a level
dropdown and a date range. Below it a monospace table of log lines: time,
level, a six character reference code, and a message. Level pips are
coloured, with yellow for warnings. One row is expanded showing an indented
JSON payload in a light grey block.`,
};

// ===============================
// * The call
// ===============================
function readKey() {
  if (!fs.existsSync(ENV_FILE)) throw new Error(`no env file at ${ENV_FILE}`);
  const line = fs.readFileSync(ENV_FILE, 'utf8')
    .split(/\r?\n/)
    .find((l) => /^\s*AI_API_KEY\s*=/.test(l));
  const key = line?.split('=').slice(1).join('=').trim().replace(/^["']|["']$/g, '');
  if (!key) throw new Error('AI_API_KEY is not set in crm/api/.env');
  return key;
}

async function generate(key, prompt, name) {
  let lastError;

  for (const { model, size, extra } of MODELS) {
    const response = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` },
      body: JSON.stringify({ model, prompt, n: 1, size, ...extra }),
    });

    if (response.ok) {
      const { data } = await response.json();
      const b64 = data?.[0]?.b64_json;
      if (!b64) throw new Error(`${model} returned no image for ${name}`);
      return { buffer: Buffer.from(b64, 'base64'), model };
    }

    // A model this key cannot use is worth falling through for. Anything
    // else (a bad key, a rate limit, a refused prompt) is not, and the
    // message is what says which.
    const body = await response.text();
    lastError = new Error(`${model} ${response.status}: ${body.slice(0, 300)}`);
    const retryable = response.status === 403 || response.status === 404
      || /must be verified|does not (have access|exist)|unsupported/i.test(body);
    if (!retryable) throw lastError;
    console.log(`  ${model} unavailable, trying the next one`);
  }

  throw lastError;
}

async function main() {
  const wanted = process.argv.slice(2);
  const names = wanted.length ? wanted : Object.keys(PAGES);

  const unknown = names.filter((n) => !PAGES[n]);
  if (unknown.length) {
    throw new Error(`no such page: ${unknown.join(', ')}. Known: ${Object.keys(PAGES).join(', ')}`);
  }

  const key = readKey();
  fs.mkdirSync(OUT_DIR, { recursive: true });

  let made = 0;
  for (const name of names) {
    process.stdout.write(`${name}… `);
    try {
      // One at a time on purpose. Parallel requests hit the image rate
      // limit on a normal key, and a half finished set is worse than a slow
      // one when somebody is waiting to look at all of them together.
      const { buffer, model } = await generate(key, PAGES[name], name);
      const file = path.join(OUT_DIR, `${name}.png`);
      fs.writeFileSync(file, buffer);
      made += 1;
      console.log(`ok (${model}, ${(buffer.length / 1024 / 1024).toFixed(1)}MB)`);
    } catch (err) {
      // Keep going. One refused prompt should not cost the other seven.
      console.log(`FAILED: ${err.message}`);
    }
  }

  console.log(`\n${made} of ${names.length} written to ${OUT_DIR}`);
  return undefined;
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
